image: node:latest
before_script:
    - npm install
stages:
    - build
    - deploy
job1:
    stage: build
    script: 
    - npm run build
    only:
    - master
job2:
    stage: deploy
    script:
    - cp -r build/* public
    only:
    - master